function applyPublicationAxes(ax)
%APPLYPUBLICATIONAXES Apply shared publication axis styling.
    set(ax, ...
        'FontName', 'Arial', ...
        'FontSize', 16, ...
        'FontWeight', 'bold', ...
        'TickDir', 'out', ...
        'Box', 'off', ...
        'LineWidth', 1.1, ...
        'XGrid', 'off', ...
        'YGrid', 'off', ...
        'Layer', 'top');

    try
        ax.XLabel.FontName = 'Arial';
        ax.XLabel.FontWeight = 'bold';
        ax.XLabel.FontSize = 18;
        ax.YLabel.FontName = 'Arial';
        ax.YLabel.FontWeight = 'bold';
        ax.YLabel.FontSize = 18;
    catch
    end
end
